"""Pipeline stage implementations (explore, design, generate, resume)."""

from __future__ import annotations

import argparse
import datetime
import json
import os
import shutil
import sys
from pathlib import Path

import ui
from pipeline.agent_runtime import require_agent_success, spawn_subagent
from pipeline.context import PROJECT_ROOT
from pipeline.contracts import (
    ArtifactKeys,
    DesignResult,
    ExplorationResult,
    StageRecord,
    StageStatus,
)
from pipeline.orchestrator import artifacts as orch_art
from pipeline.orchestrator.strategies import execute_design_strategy, execute_generate_strategy
from pipeline.pipeline_backend import run_pipeline_init
from pipeline.run_state import (
    append_completed_step,
    ensure_plot_run_layout,
    get_experiments,
    plot_debug_root,
    plot_outputs_root,
    read_manifest_stage,
    read_state,
    write_manifest_stage,
    write_state,
)


def allocate_run_dir(mode: str) -> str:
    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    if mode == "exp_plot":
        runs_dir = Path.cwd() / "notes" / "figure_runs"
        runs_dir.mkdir(parents=True, exist_ok=True)
        run_dir = runs_dir / f"run_{ts}"
        run_dir.mkdir(parents=True, exist_ok=True)
        ensure_plot_run_layout(str(run_dir))
        return str(run_dir)

    if mode == "paper_composite":
        runs_dir = Path.cwd() / "notes" / "paper_runs"
    else:
        runs_dir = Path.cwd() / "notes" / "diagram_runs"
    runs_dir.mkdir(parents=True, exist_ok=True)
    run_dir = runs_dir / f"run_{ts}"
    run_dir.mkdir(parents=True, exist_ok=True)
    os.makedirs(run_dir / "logs", exist_ok=True)
    return str(run_dir)


def _ensure_session_proposal(run_dir: str, args: argparse.Namespace) -> str:
    """Return an absolute path to the proposal file(s) for an agent-first session.

    This is only called in agent-first mode, where the agent reads files
    directly.  No text extraction is performed — PDFs, LaTeX, and other
    formats are copied into ``run_dir/`` as-is for the agent to read natively.

    If ``--proposal`` points to a directory, all recognised files are copied
    into ``run_dir/proposal/``.  The original directory path is also preserved
    on ``args._proposal_dir`` so the agent prompt can reference it.
    """
    from pipeline.proposal_loader import gather_proposal_files

    # If the user passed a natural-language instruction instead of a path,
    # write a placeholder proposal that includes the instruction text.
    proposal_instruction = getattr(args, "_proposal_instruction", None)
    if proposal_instruction:
        placeholder = os.path.join(run_dir, "proposal.md")
        if not os.path.exists(placeholder):
            Path(placeholder).write_text(
                f"# HappyFigure session\n\nUser instruction: {proposal_instruction}\n",
                encoding="utf-8",
            )
        return placeholder

    raw = os.path.abspath(args.proposal) if getattr(args, "proposal", None) else ""

    if raw and os.path.isdir(raw):
        # Copy all proposal-relevant files into run_dir/proposal/ for the agent.
        files = gather_proposal_files(Path(raw))
        if not files:
            ui.warn(f"Proposal directory {raw} contains no recognised files — generating placeholder")
            placeholder = os.path.join(run_dir, "proposal.md")
            Path(placeholder).write_text(
                "# HappyFigure session\n\nNo proposal files found in directory.\n",
                encoding="utf-8",
            )
            return placeholder

        if len(files) > 20:
            ui.warn(f"Proposal directory has {len(files)} files — using first 20")
            files = files[:20]

        proposal_dir = os.path.join(run_dir, "proposal")
        os.makedirs(proposal_dir, exist_ok=True)
        for f in files:
            dst = os.path.join(proposal_dir, f.name)
            if not os.path.exists(dst):
                shutil.copy2(str(f), dst)
        return proposal_dir

    if raw:
        # Single file — copy into run_dir so the agent has it locally.
        dst = os.path.join(run_dir, Path(raw).name)
        if not os.path.exists(dst):
            shutil.copy2(raw, dst)
        return dst

    proposal = os.path.join(run_dir, "proposal.md")
    Path(proposal).write_text(
        "# HappyFigure session\n\nAutogenerated placeholder proposal for agent-session mode.\n",
        encoding="utf-8",
    )
    return proposal


def prepare_agent_session_run(args: argparse.Namespace, mode: str) -> str:
    run_dir = os.path.abspath(getattr(args, "resume", "")) if getattr(args, "resume", None) else allocate_run_dir(mode)
    os.makedirs(run_dir, exist_ok=True)

    if mode == "exp_plot":
        ensure_plot_run_layout(run_dir)
    elif mode == "paper_composite":
        orch_art.ensure_paper_composite_layout(run_dir)
    else:
        os.makedirs(os.path.join(run_dir, "logs"), exist_ok=True)

    proposal = _ensure_session_proposal(run_dir, args)
    # experiments_dir may be comma-separated (already absolute from _ensure_compat_attrs).
    # Use the first directory for run_pipeline_init (state.json stores a single path).
    raw_exp = getattr(args, "experiments_dir", None) or ""
    first_experiments_dir = raw_exp.split(",")[0].strip() if raw_exp else ""
    experiments_dir = first_experiments_dir

    if getattr(args, "drawing_image", None):
        src = os.path.abspath(args.drawing_image)
        dst = os.path.join(run_dir, "figure.png")
        if not os.path.exists(dst):
            shutil.copy2(src, dst)

    state_path = os.path.join(run_dir, "state.json")
    if not os.path.exists(state_path):
        run_pipeline_init(
            run_dir,
            proposal,
            experiments_dir,
            mode=mode,
            llm_preset=getattr(args, "llm_preset", None),
        )

    if getattr(args, "drawing_image", None) and os.path.exists(state_path):
        state = read_state(run_dir)
        state["user_provided_image"] = True
        state["generated_image_path"] = os.path.join(run_dir, "figure.png")
        write_state(run_dir, state)

    return run_dir


def build_orchestrator_session_prompt(
    run_dir: str,
    args: argparse.Namespace,
    mode: str,
) -> str:
    proposal = _ensure_session_proposal(run_dir, args)
    raw_exp = getattr(args, "experiments_dir", None) or ""
    results_dirs = [d.strip() for d in raw_exp.split(",") if d.strip()]
    results_display = ", ".join(results_dirs) if results_dirs else "(none)"
    execution = getattr(args, "execution", "sequential")

    # If --proposal pointed to a directory, tell the agent so it can explore
    # beyond the concatenated file we saved.
    proposal_dir = getattr(args, "_proposal_dir", None)
    proposal_instruction = getattr(args, "_proposal_instruction", None)
    results_instruction = getattr(args, "_results_instruction", None)

    proposal_info = f"Proposal path: {proposal}. "
    if proposal_dir:
        proposal_info += f"Proposal source directory (explore for additional context): {proposal_dir}. "
    if proposal_instruction:
        proposal_info += f"User proposal instruction: {proposal_instruction}. "
    if results_instruction:
        proposal_info += f"User results instruction: {results_instruction}. "

    common = (
        f"Run directory: {run_dir}. "
        + proposal_info
        + (
            f"Results directories: {results_display}. "
            if len(results_dirs) > 1
            else f"Results directory: {results_display}. "
        )
        + f"Artifact layout source of truth: {PROJECT_ROOT / 'pipeline' / 'orchestrator' / 'artifacts.py'}. "
        "You are the single main HappyFigure orchestrator session. "
        "You may spawn bounded subagents when useful, but you keep global state, artifact consistency, "
        "and final output ownership. Write files directly to disk. "
        "Do NOT modify run_manifest.json; Python will index outputs after you finish. "
    )
    # Inject feedback/preference file paths (always check — preferences persist
    # across runs even without --review; review feedback only exists after --review).
    from pipeline.feedback import collect_feedback_paths

    paths = collect_feedback_paths(run_dir, stage="all")
    if paths:
        listing = "; ".join(paths)
        common += (
            f"Feedback/preference files available: {listing}. "
            "Read relevant files before each stage. "
            "Route [style] feedback to STYLE, [data] to EXPLORE, [code] to CODE. "
        )
    if mode == "exp_plot":
        return (
            common + f"Plot execution strategy: {execution}. "
            "Workflow: "
            "1) EXPLORE: first do a quick directory scan (find/ls) to count files and top-level subdirs. "
            "If the results dir is small (≤100 files or ≤5 subdirs), spawn one @data-explore for the whole dir. "
            "If large (>100 files AND >5 subdirs), partition subdirs into groups and spawn multiple @data-explore "
            "subagents in one turn (parallel). Each scoped agent writes exploration_part_N.md; you then merge "
            "into a unified exploration_report.md and exploration_summary.json. "
            "Optionally spawn @code-explore to inspect existing scripts and "
            "write code_exploration_report.md. Then read the exploration outputs and write per-experiment "
            "experiments/<exp>/description.md files. "
            "2) STYLE: spawn @planner-stylist with the exploration report, summary, and experiment list. "
            "It will write global_style.md, multi_figure_plan.md, and experiments/<exp>/styled_spec.md for every experiment. "
            "Then write design_summary.json yourself. "
            "For beam runs, also spawn @style-variant per experiment to write experiments/<exp>/styled_spec_sN.md variants. "
            "3) CODE: "
            "for sequential, write/iterate figure_code.py yourself and spawn @figure-critic for review; "
            "for parallel and beam, spawn @code-agent subagents. IMPORTANT: always include in the task prompt: "
            "run_dir, experiment slug, work_dir, output_dir, styled_spec path, iteration number (1-based), "
            "and max_iterations. For retries (iteration > 1), include prior critic feedback. "
            "For beam variants, include the variant ID (s0, s1, ...). "
            "EARLY STOP: once a critic returns ACCEPT for an experiment, promote its figure and remove it "
            "from the pending set. Only retry experiments with NEEDS_IMPROVEMENT. "
            "For beam: run iteration 1 for ALL experiments, then select the winning style variant "
            "by highest aggregate score across experiments. Lock that style for all subsequent iterations "
            "to ensure cross-figure palette consistency. "
            "Collect results, rank/select survivors, and promote final outputs to outputs/<exp>/figure.png. "
            "outputs/<exp>/ must contain ONLY figure.png — all other artifacts stay in experiments/<exp>/. "
            "4) COMPOSE: if multi_figure_plan.md contains a 'Paper Figure Mapping' section, "
            "assemble individual experiment panels into composite paper figures and save to outputs/paper_figures/. "
            "5) Ensure each experiment ends with figure_code.py and critic_result.json in experiments/<exp>/ and "
            "figure.png in outputs/<exp>/. "
            "6) Write a concise final summary to run_summary.md."
        )

    if mode == "paper_composite":
        execution = getattr(args, "execution", "parallel")
        return (
            common + f"Paper-level composite mode. Execution: {execution}. "
            "Generate ALL figures for the paper — statistical plots, diagrams, and hybrids — in one run. "
            "1) DISCOVER: spawn @data-explore and @method-explore in parallel. "
            "After both return, classify each figure by type "
            "(statistical/diagram/hybrid/placeholder). "
            "IMPORTANT: if the proposal describes a schematic or architecture diagram, classify as 'diagram' (generatable=true), NOT 'placeholder'. "
            "Before marking ANY panel as placeholder, verify the data is truly missing — "
            "check exploration_summary.json 'recoverable_data' field AND the exploration report's 'Recoverable Data' section. "
            "If eval scripts + inputs exist, write a recovery script to data_recovery/ and execute it via bash, "
            "then classify the panel as 'statistical' with data_source pointing to the recovered output. "
            "Write figure_classification.json with per-panel type, data_source, generatable flag. "
            "If no proposal provided: infer figures from data patterns. "
            "Every proposed figure MUST cite specific data files. "
            "Max 8 figures without explicit proposal. "
            "2) PLAN: spawn @planner-stylist for statistical panels "
            "(writes global_style.md, per-panel styled_spec.md). "
            "Write assembly_spec/<figure>.json with nested row-based layout trees for each figure. "
            "Write color_registry.json for cross-figure color consistency. "
            "Write paper_figure_plan.md and design_summary.json. "
            "3) GENERATE: route panels by type. "
            "Statistical panels: spawn @code-agent per panel. "
            "CRITICAL: include global_style.md AND color_registry.json paths in EVERY code-agent prompt "
            "so all panels use the same colors, fonts, and spine rules. "
            "Diagram panels: for EACH diagram, create a per-panel working dir at experiments/<slug>/diagram/ "
            "(avoids artifact collisions). Copy method_description.md + state.json there. "
            "Spawn @svg-builder then @svg-refiner using that per-panel dir as run_dir. "
            "Services are running (SAM3:8001, OCR:8002, BEN2:8003). "
            "After completion, copy output to panels/<figure>/<panel>/. "
            "Do NOT use @svg-author — service-based pipeline produces higher quality. "
            "Placeholder panels: generate labeled gray placeholder PNGs. "
            "Panel slug convention: {figure_id}__{panel_id} (e.g., figure_1__a). "
            "4) ASSEMBLE: for each figure, read assembly_spec, write a PIL-based assembly script "
            "(use PIL Image.open/paste for pixel-perfect composition without blur; fall back to matplotlib GridSpec "
            "with aspect='equal' if PIL unavailable). Tight spacing, 14pt bold labels, 300 DPI, white background. "
            "Run @figure-critic in assembly mode on each assembled figure. "
            "Iterate assembly if NEEDS_IMPROVEMENT (max 3). "
            "Save to outputs/paper_figures/Figure_N.{png,pdf}. "
            "5) Verify all figures exist, write run_summary.md."
        )

    code_step = {
        "agent_svg": (
            "CODE: sketch mode. Write method_description.md and diagram_design_spec.md, then write the SVG directly "
            "or spawn @svg-author, review with @figure-critic if useful, iterate, and produce "
            "method_architecture.svg and method_architecture.png."
        ),
        "composite": (
            "CODE: composite diagram mode. Services are already running for the build phase. "
            "Spawn @svg-builder (generates raster, segments, builds SVG), then @svg-refiner. "
            "If skip_viz_compose is false, spawn @viz-composer after refinement. "
            "Do NOT write SVG directly."
        ),
    }[mode]
    return (
        common
        + f"Diagram mode: {mode}. "
        + (
            "EXPLORE: if a results directory is present, optionally spawn @data-explore for visualization context. "
            "Read the proposal yourself and write method_description.md. "
            "STYLE: write diagram_design_spec.md and design_summary.json. "
            f"{code_step} "
            "Write a concise final summary to run_summary.md."
        )
    )


def _collect_plot_explore_artifacts(run_dir: str, artifacts: dict[str, str]) -> None:
    """Shared artifact collection for plot-related explore output."""
    for key, rel in (
        (ArtifactKeys.REPORT, orch_art.PLOT_EXPLORATION_REPORT),
        (ArtifactKeys.SUMMARY_JSON, orch_art.PLOT_EXPLORATION_SUMMARY),
    ):
        if os.path.exists(os.path.join(run_dir, rel)):
            artifacts[key] = rel
    extra = "code_exploration_report.md"
    if os.path.exists(os.path.join(run_dir, extra)):
        artifacts["code_exploration_report"] = extra
    for exp in get_experiments(run_dir):
        rel = os.path.relpath(orch_art.experiment_description_path(run_dir, exp), run_dir)
        if os.path.exists(os.path.join(run_dir, rel)):
            artifacts[f"description/{exp}"] = rel


def collect_explore_artifacts(run_dir: str, mode: str) -> dict[str, str]:
    artifacts: dict[str, str] = {}
    if mode == "paper_composite":
        _collect_plot_explore_artifacts(run_dir, artifacts)
        # Paper composite also collects method exploration + figure classification
        for key, rel in ((ArtifactKeys.METHOD_DESC, "method_description.md"),):
            if os.path.exists(os.path.join(run_dir, rel)):
                artifacts[key] = rel
        fc_rel = orch_art.FIGURE_CLASSIFICATION
        if os.path.exists(os.path.join(run_dir, fc_rel)):
            artifacts[ArtifactKeys.FIGURE_CLASSIFICATION] = fc_rel
    elif mode == "exp_plot":
        _collect_plot_explore_artifacts(run_dir, artifacts)
    else:
        for key, rel in (
            (ArtifactKeys.REPORT, "method_exploration_report.md"),
            (ArtifactKeys.METHOD_DESC, "method_description.md"),
            (ArtifactKeys.SUMMARY_JSON, "method_exploration_summary.json"),
            (ArtifactKeys.IMAGE, "figure.png"),
        ):
            if os.path.exists(os.path.join(run_dir, rel)):
                artifacts[key] = rel
    return artifacts


def validate_agent_session_outputs(run_dir: str, mode: str, design: DesignResult) -> list[str]:
    missing: list[str] = []

    if mode == "paper_composite":
        required = [
            orch_art.FIGURE_CLASSIFICATION,
            orch_art.PAPER_FIGURE_PLAN,
            orch_art.DESIGN_SUMMARY,
            "run_summary.md",
        ]
        for rel in required:
            if not os.path.exists(os.path.join(run_dir, rel)):
                missing.append(rel)
        # Check assembly specs directory has at least one spec
        spec_dir = orch_art.assembly_spec_dir(run_dir)
        if os.path.isdir(spec_dir):
            specs = [f for f in os.listdir(spec_dir) if f.endswith(".json")]
            if not specs:
                missing.append(f"{orch_art.ASSEMBLY_SPEC_DIR}/*.json")
        else:
            missing.append(orch_art.ASSEMBLY_SPEC_DIR)
        # Check paper figures directory has at least one output
        pf_dir = orch_art.paper_figures_dir(run_dir)
        if os.path.isdir(pf_dir):
            figs = [f for f in os.listdir(pf_dir) if f.endswith((".png", ".pdf"))]
            if not figs:
                missing.append(f"{orch_art.OUTPUTS_DIR}/{orch_art.PAPER_FIGURES_DIR}/*.png")
        else:
            missing.append(f"{orch_art.OUTPUTS_DIR}/{orch_art.PAPER_FIGURES_DIR}")
        return sorted(set(missing))

    if mode == "exp_plot":
        required = [
            orch_art.PLOT_EXPLORATION_REPORT,
            orch_art.PLOT_EXPLORATION_SUMMARY,
            orch_art.GLOBAL_STYLE,
            orch_art.MULTI_FIGURE_PLAN,
            orch_art.DESIGN_SUMMARY,
            "run_summary.md",
        ]
        for rel in required:
            if not os.path.exists(os.path.join(run_dir, rel)):
                missing.append(rel)
        for exp in design.experiments:
            exp_required = [
                os.path.relpath(orch_art.experiment_description_path(run_dir, exp), run_dir),
                os.path.relpath(orch_art.experiment_styled_spec_path(run_dir, exp), run_dir),
                os.path.join("outputs", exp, "figure.png"),
            ]
            for rel in exp_required:
                if not os.path.exists(os.path.join(run_dir, rel)):
                    missing.append(rel)
    else:
        required = [
            "method_description.md",
            orch_art.DIAGRAM_DESIGN_SPEC,
            orch_art.DESIGN_SUMMARY,
            "run_summary.md",
        ]
        for rel in required:
            if not os.path.exists(os.path.join(run_dir, rel)):
                missing.append(rel)

        if mode == "agent_svg":
            for rel in ("method_architecture.svg", "method_architecture.png"):
                if not os.path.exists(os.path.join(run_dir, rel)):
                    missing.append(rel)
        else:
            for rel in ("method_architecture.svg", "method_architecture.png"):
                if not os.path.exists(os.path.join(run_dir, rel)):
                    missing.append(rel)
            if mode == "composite" and not getattr(design, "skip_viz_compose", False):
                # composite output is optional at runtime, but if present we index it later
                pass

    return sorted(set(missing))


def collect_design_artifacts(
    run_dir: str, mode: str, experiments: list[str]
) -> tuple[dict[str, str], dict[str, list[str]] | None]:
    artifacts: dict[str, str] = {}
    variant_specs: dict[str, list[str]] | None = None

    if mode == "exp_plot":
        for key, rel in (
            (ArtifactKeys.GLOBAL_STYLE, orch_art.GLOBAL_STYLE),
            (ArtifactKeys.PLAN, orch_art.MULTI_FIGURE_PLAN),
            ("design_summary", orch_art.DESIGN_SUMMARY),
        ):
            if os.path.exists(os.path.join(run_dir, rel)):
                artifacts[key] = rel
        for exp in experiments:
            rel = os.path.relpath(orch_art.experiment_styled_spec_path(run_dir, exp), run_dir)
            if os.path.exists(os.path.join(run_dir, rel)):
                artifacts[ArtifactKeys.spec(exp)] = rel
            variant_paths = []
            variant_idx = 0
            while True:
                variant_rel = orch_art.beam_styled_spec_rel_path(exp, variant_idx)
                if not os.path.exists(os.path.join(run_dir, variant_rel)):
                    break
                variant_paths.append(variant_rel)
                variant_idx += 1
            if variant_paths:
                variant_specs = variant_specs or {}
                variant_specs[exp] = variant_paths
        if variant_specs:
            vs_path = os.path.join(run_dir, "beam_variant_specs.json")
            with open(vs_path, "w", encoding="utf-8") as f:
                json.dump(variant_specs, f, indent=2)
            artifacts["beam_variant_specs"] = "beam_variant_specs.json"
    elif mode == "paper_composite":
        for key, rel in (
            (ArtifactKeys.FIGURE_CLASSIFICATION, orch_art.FIGURE_CLASSIFICATION),
            (ArtifactKeys.PAPER_FIGURE_PLAN, orch_art.PAPER_FIGURE_PLAN),
            (ArtifactKeys.GLOBAL_STYLE, orch_art.GLOBAL_STYLE),
            ("design_summary", orch_art.DESIGN_SUMMARY),
        ):
            if os.path.exists(os.path.join(run_dir, rel)):
                artifacts[key] = rel
        # Index assembly specs
        spec_dir = orch_art.assembly_spec_dir(run_dir)
        if os.path.isdir(spec_dir):
            for fname in sorted(os.listdir(spec_dir)):
                if fname.endswith(".json"):
                    fig_id = fname.replace(".json", "")
                    artifacts[f"assembly_spec/{fig_id}"] = os.path.join(orch_art.ASSEMBLY_SPEC_DIR, fname)
        # Index per-panel experiments
        for exp in experiments:
            rel = os.path.relpath(orch_art.experiment_styled_spec_path(run_dir, exp), run_dir)
            if os.path.exists(os.path.join(run_dir, rel)):
                artifacts[ArtifactKeys.spec(exp)] = rel
    else:
        for key, rel in (
            (ArtifactKeys.PRIMARY_DESIGN, "method_description.md"),
            ("diagram_design_spec", orch_art.DIAGRAM_DESIGN_SPEC),
            ("design_summary", orch_art.DESIGN_SUMMARY),
        ):
            if os.path.exists(os.path.join(run_dir, rel)):
                artifacts[key] = rel
        if os.path.exists(os.path.join(run_dir, "figure.png")):
            artifacts[ArtifactKeys.IMAGE] = "figure.png"

    return artifacts, variant_specs


def sync_agent_session_manifest(run_dir: str, args: argparse.Namespace, mode: str) -> DesignResult:
    experiments = get_experiments(run_dir) if mode in ("exp_plot", "paper_composite") else []
    explore_artifacts = collect_explore_artifacts(run_dir, mode)
    design_artifacts, variant_specs = collect_design_artifacts(run_dir, mode, experiments)
    design = DesignResult(mode=mode, artifacts=design_artifacts, experiments=experiments, variant_specs=variant_specs)
    generate_artifacts = collect_generate_artifacts(run_dir, mode, experiments)
    summary_rel = "run_summary.md"
    if os.path.exists(os.path.join(run_dir, summary_rel)):
        generate_artifacts["run_summary"] = summary_rel

    missing = validate_agent_session_outputs(run_dir, mode, design)
    if missing:
        raise RuntimeError("Agent-session run is missing required outputs: " + ", ".join(missing))

    now = datetime.datetime.now().isoformat()
    write_manifest_stage(
        run_dir,
        "explore",
        StageRecord(
            status=StageStatus.COMPLETED,
            completed_at=now,
            artifacts=explore_artifacts,
            experiments=experiments,
            metadata=stage_metadata(run_dir, mode, args, stage="explore"),
        ),
        mode=mode,
    )
    write_manifest_stage(
        run_dir,
        "design",
        StageRecord(
            status=StageStatus.COMPLETED,
            completed_at=now,
            artifacts=design_artifacts,
            experiments=experiments,
            metadata=stage_metadata(run_dir, mode, args, stage="design", design=design),
        ),
        mode=mode,
    )
    write_manifest_stage(
        run_dir,
        "generate",
        StageRecord(
            status=StageStatus.COMPLETED,
            completed_at=now,
            artifacts=generate_artifacts,
            experiments=experiments,
            metadata=stage_metadata(run_dir, mode, args, stage="generate", design=design),
        ),
        mode=mode,
    )
    return design


def _scan_results_dir(results_dir: str) -> tuple[int, list[str]]:
    """Quick scan: count files and list top-level subdirectories.

    *results_dir* may be a comma-separated list of directories; all are
    scanned and the results are aggregated.

    Returns (file_count, subdir_full_paths) where subdir_full_paths are
    absolute paths so callers don't need to reconstruct the parent.
    """
    dirs = [d.strip() for d in results_dir.split(",") if d.strip()] if results_dir else []
    total_files = 0
    all_subdirs: list[str] = []
    for rd in dirs:
        if not os.path.isdir(rd):
            continue
        all_subdirs.extend(
            os.path.join(rd, d) for d in os.listdir(rd) if os.path.isdir(os.path.join(rd, d)) and not d.startswith(".")
        )
        total_files += sum(len(files) for _, _, files in os.walk(rd))
    return total_files, sorted(set(all_subdirs))


def _partition_subdirs(subdirs: list[str], max_per_group: int = 5) -> list[list[str]]:
    """Split subdirectories into roughly equal groups."""
    if not subdirs:
        return []
    n_groups = max(1, (len(subdirs) + max_per_group - 1) // max_per_group)
    groups: list[list[str]] = [[] for _ in range(n_groups)]
    for i, sd in enumerate(subdirs):
        groups[i % n_groups].append(sd)
    return [g for g in groups if g]


def _merge_exploration_parts(run_dir: str, part_paths: list[str]) -> None:
    """Merge partial exploration reports into the unified report and summary."""
    report_path = orch_art.plot_exploration_report_path(run_dir)
    summary_path = os.path.join(run_dir, orch_art.PLOT_EXPLORATION_SUMMARY)

    # Merge report text
    merged_lines = ["## Experiment Exploration Report\n"]
    for pp in part_paths:
        if os.path.exists(pp):
            merged_lines.append(Path(pp).read_text())
            merged_lines.append("\n---\n")
    Path(report_path).write_text("\n".join(merged_lines))

    # Merge summary JSONs
    merged_summary: dict = {
        "experiments_found": [],
        "methods": [],
        "key_files": {},
        "data_formats": {},
        "data_quality": {"complete": [], "issues": {}},
        "proposal_claims": [],
    }
    for pp in part_paths:
        sp = pp.replace(".md", ".json")
        if not os.path.exists(sp):
            continue
        try:
            part = json.loads(Path(sp).read_text())
        except (json.JSONDecodeError, OSError):
            continue
        merged_summary["experiments_found"].extend(part.get("experiments_found", []))
        merged_summary["methods"].extend(part.get("methods", []))
        merged_summary["key_files"].update(part.get("key_files", {}))
        for fmt, cnt in part.get("data_formats", {}).items():
            merged_summary["data_formats"][fmt] = merged_summary["data_formats"].get(fmt, 0) + cnt
        dq = part.get("data_quality", {})
        merged_summary["data_quality"]["complete"].extend(dq.get("complete", []))
        merged_summary["data_quality"]["issues"].update(dq.get("issues", {}))
        merged_summary["proposal_claims"].extend(part.get("proposal_claims", []))
    # Deduplicate lists
    merged_summary["experiments_found"] = sorted(set(merged_summary["experiments_found"]))
    merged_summary["methods"] = sorted(set(merged_summary["methods"]))
    merged_summary["data_quality"]["complete"] = sorted(set(merged_summary["data_quality"]["complete"]))
    merged_summary["proposal_claims"] = list(dict.fromkeys(merged_summary["proposal_claims"]))
    Path(summary_path).write_text(json.dumps(merged_summary, indent=2) + "\n")


# Thresholds for parallel exploration (python-stages mode).
_PARALLEL_EXPLORE_FILE_THRESHOLD = 100
_PARALLEL_EXPLORE_SUBDIR_THRESHOLD = 5


def step_explore_plot(args: argparse.Namespace) -> str:
    """Plot mode: run data-explore and pipeline init.

    For large results directories (>100 files AND >5 top-level subdirs),
    partitions the directory and spawns parallel data-explore subagents.
    """
    proposal = os.path.abspath(args.proposal) if args.proposal else ""
    raw_exp = getattr(args, "experiments_dir", None) or ""
    experiments_dir = raw_exp  # may be comma-separated (already absolute)
    # Use the first dir for run_pipeline_init (state.json stores a single path)
    first_experiments_dir = experiments_dir.split(",")[0].strip() if experiments_dir else ""

    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    runs_dir = Path.cwd() / "notes" / "figure_runs"
    runs_dir.mkdir(parents=True, exist_ok=True)
    run_dir = str(runs_dir / f"run_{ts}")
    os.makedirs(run_dir, exist_ok=True)
    ensure_plot_run_layout(run_dir)

    report_path = orch_art.plot_exploration_report_path(run_dir)
    summary_json_path = os.path.join(run_dir, orch_art.PLOT_EXPLORATION_SUMMARY)

    # Quick scan to decide single vs parallel exploration (scans all dirs)
    file_count, subdirs = _scan_results_dir(experiments_dir)
    use_parallel = file_count > _PARALLEL_EXPLORE_FILE_THRESHOLD and len(subdirs) > _PARALLEL_EXPLORE_SUBDIR_THRESHOLD

    if use_parallel:
        ui.info(f"Large results dir ({file_count} files, {len(subdirs)} subdirs) — running parallel exploration")
        groups = _partition_subdirs(subdirs)
        part_paths: list[str] = []

        from concurrent.futures import ThreadPoolExecutor, as_completed

        def _run_part(idx: int, group: list[str]) -> tuple[int, int]:
            part_path = os.path.join(run_dir, f"exploration_part_{idx}.md")
            part_json = os.path.join(run_dir, f"exploration_part_{idx}.json")
            part_paths.append(part_path)
            # group items are already full paths from _scan_results_dir
            scoped_dirs = ", ".join(group)
            prompt = (
                f"Explore the experiment data in a SCOPED subset of directories. "
                f"Proposal: {proposal}. "
                f"Scoped subdirectories (explore ONLY these): {scoped_dirs}. "
                f"Write the exploration report to {part_path}. "
                f"Also write the structured summary JSON to {part_json}. "
                f"Do NOT invoke planner-stylist or code-agent. "
                f"When both files are saved, you are done."
            )
            rc = spawn_subagent(
                "data-explore",
                prompt,
                verbose=args.verbose,
                log_dir=os.path.join(run_dir, "logs"),
                log_name=f"data-explore-part{idx}",
                label=f"part-{idx}",
            )
            return idx, rc

        # Spawn parallel exploration subagents
        with ThreadPoolExecutor(max_workers=min(len(groups), 4)) as pool:
            futures = {pool.submit(_run_part, i, g): i for i, g in enumerate(groups)}
            for fut in as_completed(futures):
                idx, rc = fut.result()
                require_agent_success(f"data-explore-part{idx}", rc)

        # Merge partial reports
        _merge_exploration_parts(run_dir, part_paths)
        ui.info(f"Merged {len(part_paths)} partial exploration reports")
    else:
        # Single exploration (original path)
        results_label = "Results directories" if "," in experiments_dir else "Results directory"
        prompt = (
            f"Explore the experiment data and write a complete exploration report. "
            f"Proposal: {proposal}. "
            f"{results_label}: {experiments_dir}. "
            f"Write the full report to {report_path}. "
            f"Also write the structured summary JSON to {summary_json_path}. "
            f"Do NOT invoke planner-stylist or code-agent — the orchestrator handles that. "
            f"When the report is saved, you are done."
        )
        rc = spawn_subagent(
            "data-explore",
            prompt,
            verbose=args.verbose,
            log_dir=os.path.join(run_dir, "logs"),
            log_name="data-explore",
        )
        require_agent_success("data-explore", rc)

    if not os.path.exists(report_path):
        ui.error(f"Exploration report not found at {report_path}")
        sys.exit(1)

    ui.info(f"Running pipeline init for {run_dir}...")
    mode = getattr(args, "mode", None) or "exp_plot"
    llm_preset = getattr(args, "llm_preset", None)
    run_pipeline_init(run_dir, proposal, first_experiments_dir, mode=mode, llm_preset=llm_preset)

    state = read_state(run_dir)
    state["exploration_report_path"] = report_path
    state["outputs_dir"] = plot_outputs_root(run_dir)
    state["debug_dir"] = plot_debug_root(run_dir)
    append_completed_step(state, "exp_explore")
    write_state(run_dir, state)

    ui.success(f"Data exploration complete. Run dir: {run_dir}")
    return run_dir


def write_explore_summary(run_dir: str, mode: str, args: argparse.Namespace) -> None:
    """Mechanical exploration summary JSON after explore (orchestrator fallback)."""
    if mode == "exp_plot":
        summary_path = os.path.join(run_dir, orch_art.PLOT_EXPLORATION_SUMMARY)
        report_path = orch_art.plot_exploration_report_path(run_dir)
    else:
        summary_path = os.path.join(run_dir, "method_exploration_summary.json")
        report_path = os.path.join(run_dir, "method_exploration_report.md")

    if os.path.exists(summary_path):
        return

    summary: dict = {"generated_by": "orchestrator_fallback"}

    if os.path.exists(report_path):
        with open(report_path, encoding="utf-8") as f:
            content = f.read()
        summary["report_lines"] = len(content.splitlines())
        summary["report_chars"] = len(content)

    raw_exp = getattr(args, "experiments_dir", None) or ""
    exp_dirs = [d.strip() for d in raw_exp.split(",") if d.strip()]
    format_counts: dict[str, int] = {}
    for rd in exp_dirs:
        if not os.path.isdir(rd):
            continue
        for dirpath, _dirs, files in os.walk(rd):
            for fname in files:
                ext = os.path.splitext(fname)[1].lower().lstrip(".")
                if ext in ("csv", "json", "jsonl", "tsv", "parquet", "npy", "npz", "pkl", "h5"):
                    format_counts[ext] = format_counts.get(ext, 0) + 1
    if format_counts:
        summary["data_formats"] = format_counts

    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)


def _read_explore_experiments(run_dir: str, mode: str) -> list[str]:
    if mode != "exp_plot":
        return []

    summary_path = os.path.join(run_dir, orch_art.PLOT_EXPLORATION_SUMMARY)
    if not os.path.exists(summary_path):
        return []

    try:
        with open(summary_path, encoding="utf-8") as f:
            payload = json.load(f)
    except (OSError, json.JSONDecodeError):
        return []

    experiments = payload.get("experiments_found") or []
    if not isinstance(experiments, list):
        return []
    cleaned = [str(exp).strip() for exp in experiments if str(exp).strip()]
    return sorted(dict.fromkeys(cleaned))


def stage_explore(args: argparse.Namespace, mode: str) -> ExplorationResult:
    from pipeline.drawing import step_init_drawing_image, step_method_explore

    if mode == "exp_plot":
        run_dir = step_explore_plot(args)
        write_explore_summary(run_dir, mode, args)
        return ExplorationResult(
            run_dir=run_dir,
            mode=mode,
            artifacts={
                ArtifactKeys.REPORT: orch_art.PLOT_EXPLORATION_REPORT,
                ArtifactKeys.SUMMARY_JSON: orch_art.PLOT_EXPLORATION_SUMMARY,
            },
            experiments=_read_explore_experiments(run_dir, mode),
        )

    has_drawing_image = getattr(args, "drawing_image", None) is not None
    if has_drawing_image:
        label = "composite" if mode == "composite" else "method drawing"
        ui.info(f"Starting {label} pipeline (2-agent mode, user-provided image)")
        run_dir = step_init_drawing_image(args)
        return ExplorationResult(
            run_dir=run_dir,
            mode=mode,
            artifacts={ArtifactKeys.IMAGE: "figure.png"},
            experiments=[],
        )

    if mode == "agent_svg":
        ui.info("Starting agent-driven SVG pipeline (no services)")
    elif mode == "composite":
        ui.info("Starting composite pipeline (4-agent mode)")
    else:
        ui.info("Starting method drawing pipeline (3-agent mode)")

    run_dir = step_method_explore(args)
    write_explore_summary(run_dir, mode, args)
    return ExplorationResult(
        run_dir=run_dir,
        mode=mode,
        artifacts={
            ArtifactKeys.REPORT: "method_exploration_report.md",
            ArtifactKeys.METHOD_DESC: "method_description.md",
            ArtifactKeys.SUMMARY_JSON: "method_exploration_summary.json",
        },
        experiments=[],
    )


def stage_design(
    exploration: ExplorationResult,
    args: argparse.Namespace,
    mode: str,
) -> DesignResult:
    return execute_design_strategy(exploration, args, mode)


def collect_generate_artifacts(
    run_dir: str,
    mode: str,
    experiments: list[str],
) -> dict[str, str]:
    artifacts: dict[str, str] = {}
    if mode == "exp_plot":
        for exp in experiments:
            fig = os.path.join("outputs", exp, "figure.png")
            if os.path.exists(os.path.join(run_dir, fig)):
                artifacts[ArtifactKeys.figure(exp)] = fig
            # Critic result lives in workspace (experiments/<exp>/), not outputs/
            ws_crit = os.path.join(
                orch_art.EXPERIMENTS_DIR,
                exp,
                orch_art.CRITIC_RESULT,
            )
            if os.path.exists(os.path.join(run_dir, ws_crit)):
                artifacts[f"critic_workspace/{exp}"] = ws_crit
            # Backward compat: check old location in outputs/<exp>/
            elif os.path.exists(os.path.join(run_dir, "outputs", exp, orch_art.CRITIC_RESULT)):
                artifacts[f"critic_workspace/{exp}"] = os.path.join("outputs", exp, orch_art.CRITIC_RESULT)
        # Composite paper figures
        pf_dir = os.path.join(run_dir, "outputs", orch_art.PAPER_FIGURES_DIR)
        if os.path.isdir(pf_dir):
            for fname in sorted(os.listdir(pf_dir)):
                if fname.endswith((".png", ".pdf")):
                    rel = os.path.join("outputs", orch_art.PAPER_FIGURES_DIR, fname)
                    artifacts[f"paper_figure/{fname}"] = rel
    else:
        for name in ("method_architecture.svg", "method_architecture.png"):
            if os.path.exists(os.path.join(run_dir, name)):
                artifacts[name] = name
        composed = "method_architecture_composed.png"
        if os.path.exists(os.path.join(run_dir, composed)):
            artifacts["composed"] = composed
    return artifacts


def stage_metadata(
    run_dir: str,
    mode: str,
    args: argparse.Namespace,
    *,
    stage: str,
    design: DesignResult | None = None,
) -> dict[str, object]:
    metadata: dict[str, object] = {
        "mode": mode,
        "stage": stage,
        "services_required": mode == "composite" and stage == "generate",
    }

    if mode == "exp_plot":
        metadata["execution_strategy"] = getattr(args, "execution", "sequential")

    if design is not None:
        metadata["experiment_count"] = len(design.experiments)
        if mode == "exp_plot" and design.experiments:
            metadata["experiment_artifacts"] = {
                exp: orch_art.plot_experiment_index_entry(
                    run_dir,
                    exp,
                    beam_variant_specs=(design.variant_specs or {}).get(exp),
                )
                for exp in design.experiments
            }
        if design.variant_specs:
            metadata["beam_variant_experiments"] = len(design.variant_specs)

    if mode == "composite" and stage == "generate":
        metadata["skip_viz_compose"] = bool(getattr(args, "skip_viz_compose", False))

    return metadata


def stage_generate(
    run_dir: str,
    args: argparse.Namespace,
    mode: str,
    design: DesignResult,
) -> None:
    execute_generate_strategy(run_dir, args, mode, design)

    if mode == "composite" and getattr(args, "skip_viz_compose", False):
        ui.dim("Skipping viz-composer (--skip-viz-compose)")

    gen_artifacts = collect_generate_artifacts(run_dir, mode, design.experiments)
    write_manifest_stage(
        run_dir,
        "generate",
        StageRecord(
            status=StageStatus.COMPLETED,
            completed_at=datetime.datetime.now().isoformat(),
            artifacts=gen_artifacts,
            experiments=design.experiments,
            metadata=stage_metadata(run_dir, mode, args, stage="generate", design=design),
        ),
    )


def try_resume(run_dir: str, mode: str) -> tuple[ExplorationResult | None, DesignResult | None]:
    explore_rec = read_manifest_stage(run_dir, "explore")
    design_rec = read_manifest_stage(run_dir, "design")

    exploration: ExplorationResult | None = None
    design: DesignResult | None = None

    if explore_rec and explore_rec.status == StageStatus.COMPLETED:
        exploration = ExplorationResult(
            run_dir=run_dir,
            mode=mode,
            artifacts=explore_rec.artifacts,
            experiments=explore_rec.experiments,
        )

    if design_rec and design_rec.status == StageStatus.COMPLETED:
        variant_specs = None
        vs_rel = design_rec.artifacts.get("beam_variant_specs")
        if vs_rel:
            vs_path = os.path.join(run_dir, vs_rel)
            if os.path.exists(vs_path):
                with open(vs_path, encoding="utf-8") as f:
                    variant_specs = json.load(f)
        elif mode == "exp_plot":
            experiment_artifacts = design_rec.metadata.get("experiment_artifacts", {})
            extracted_variants = {
                exp: data.get("beam_variant_specs", [])
                for exp, data in experiment_artifacts.items()
                if isinstance(data, dict) and data.get("beam_variant_specs")
            }
            if extracted_variants:
                variant_specs = extracted_variants

        design = DesignResult(
            mode=mode,
            artifacts=design_rec.artifacts,
            experiments=design_rec.experiments,
            variant_specs=variant_specs,
        )

    return exploration, design
